language: java
deploy:
  on:
    branch: main
  skip_cleanup: true
  provider: heroku
  app: myapp-JuanIgnacioMagaz
  api_key:
    secure: s3dRAhHV3Nw4xDopnZd3mKiJ7/pxbRDy5upi7R1QbDtAdhBrdR9h1M1M7iBTKDaU3RTn38KIqyKbH5wMLsnwgdyiomICS3xTrpjc6QMlam73Y/9PtfF+HyMAlfd87Fhwhl+vq+GZPRUVUOJKspB+3NgA4qPCg55Dfi0azXTPwRb7rwMX9wdAjFE0MHECNROnNH9kGw0P5Qd0dXpcvADAtb4HH99RyVZKlTM/dH1yW5SBj9SWuG/uXoYdXOzLE3fRkJoWqAr0P93Q6Pq4mlHx0OsfjPdM2xcSnUGZUVm27/iZ91kJYjcJlZRIp2MHpF1jADIo1CWiEG0iuWSUQgWw/tcaw+54ddXYWGTDyUNz9f/yBQCJzXYWbaGxohoqQVOZEf8+ld8e7o3Ugwq6NjkPeDfbBNEXj/Bo4BGqxjDtasWxvolB9UEx0ih7Xoj7qnSqgBK71UILsNSac0aauQY1CQg6fzh1K9es01q8f8wK6qr+YMR3TyBMfNSserSX6OKwwTd+n2Yiqvh7NRi2K5GmudzKbvF57sZPlfcX1IJl7yjShEMKn85PrM9XFLKvHL2iu61qNKG474vbFO8p4agEdgxZU+LdoPVJTOn8XfQf57439mdsP+M52MwypTUgvfNsTF5HEaDTkKm3MUudwsoRqqQEy9caa/pBUhza43/C9DI=
